name: Build and Test
run-name: ${{ github.actor }} is testing out cli init
on: [push]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    container:
      image: python
      volumes:
        - ${{ github.workspace }}:${{ github.workspace }}
    strategy:
      matrix:
        job: [build, test]

    steps:
      - name: ${{ matrix.job }}
        uses: actions/checkout@v4

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: python cli build
        run: |
          python --version
          pip install -r requirements.txt
          python ./src/cli.py init
